name 'chef-server-ctl'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef-server-ctl'
long_description 'Installs/Configures chef-server-ctl'
version '0.1.0'
